### ISSUE TITLE
【🌟Feature】I added dark-mode feature in PR#20

### ISSUE THREAD

**Issue by BoyanXu** [FallenMax/smart-toc#21]
Hi @FallenMax , I added dark-mode feature in #20 

This use `@media (prefers-color-scheme: light/dark)` feature to make the decision on when to use dark mode  (see: [this page](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme))

This is how it looks like:

<img width="1496" alt="图片" src="https://user-images.githubusercontent.com/34408790/157523224-951c46cb-4c28-4438-a107-95211be0f2cf.png">

_Originally posted by @BoyanXu in https://github.com/FallenMax/smart-toc/issues/18#issuecomment-1063312085_

**Comment by FallenMax** [comment]
@BoyanXu Hi, thanks for submitting this PR.

Sorry for not updating Smart TOC for a long time due to personal reasons, it lacks some important features like dark mode.

But now I'm putting more time into developing this project. The currently released version 0.6.1 has revamped core mechanisms such as content detection and tracking, and performs better for more scenario. Please download and try.

Other features like dark mode, find, copy are being developed and some finished. The dark mode is selected upon detecting page theme, and can be switched manually. 

However, I'm considering providing these features as paid features (mainly for motivation, because it really takes effort to make things right), and the code is not open source yet. Can I hear your thoughts on the paid version? What price will be reasonable and what features are expected?

That's said, feel free to fork this code and add features you desire (dark mode), and thanks again for contributing!

**Comment by BoyanXu** [comment]
Hi @FallenMax, I'm really happen to hear that you're putting extra time on this project!
Personally, I'm 100% supportive for the paid features. I've seen many successful add-ons (like: SimpRead) starts from free version but matures because of proper incentives like a paid plan.

I would appreciate the following features in a paid plan:
1. Dark mode
2. Width & Height control (replace tail of lengthy titles with "...")
3. Remember position on current page
4. Pin to side (like: OctoTree)

I would accept a price between 5~10 dollars. I recommend take SimpRead's pricing model as a reference (because it's proven to be successful) and branding it on places like sspai.com and appinn.com to find your beta-users

Thanks again for your wonderful work. Can't wait to see the updates!

**Comment by FallenMax** [comment]
Hi @BoyanXu, thank you so much for support and insightful suggestions! Will definitely looking into proper branding and promoting as you suggested after polishing up this product a little bit.

I've published a new version of Smart TOC which includes some paid features like dark mode, expand/collapse, more heading levels, etc. 

In return for your contribution, I have provided you Smart TOC Pro membership. I assume the email address in your GitHub profile is also your browser account. If you are using another account for Chrome/Edge, feel free to reply or drop a message at FallenMax#gmail#com :)   Looking forward to your feedback for the new version.

As for suggested pro features, here is progress or thought for each one of them:

1. Dark mode - definitely, added in pro version already, and it adapts to site theme by detecting article background, not perfect for gradient/image background though.
2. Floating mode - resizable - added in pro version 
3. Floating mode - Remember size & position on current page - currently ui state is only preserved if page is not closed/refreshed. Will consider storing this kind of state across session, but it's not easy to tell if same url always leads to same page/article/headings, this requires some more investigation.
4. Pin mode (like: OctoTree) - Smart TOC is supposed to work on all kinds of (weird/unexpected) website other than a single stable site. Producing a stable sidebar layout for them will be difficult, and even it's technically done, the result could be aesthetically wrong. Considering Pin mode is primarily targeting the "toc panel should not clutter page or cover page content" problem, I will try to investigate on some other solutions and hope there will be a working one.

Thank you again for your support and valuable opinions, hope you like the new version!  
(Let me know if account is incorrect.)
