### ISSUE TITLE
[缺陷]当页面滑动到最底部时，无法展开界面中未展开的目录

### ISSUE THREAD

**Issue by xyls184** [FallenMax/smart-toc#23]
[缺陷]当页面滑动到最底部时，无法展开界面中未展开的目录
![Screenshot-20220312181453](https://user-images.githubusercontent.com/20354136/158014218-b8a30e2f-2ed0-4af5-b5b7-72ea66cec3b7.png)
刚不小心发pull requests去了，第一次用github，非常抱歉

**Comment by FallenMax** [comment]
Looks like an old version, you can get latest version from https://chrome.google.com/webstore/detail/smart-toc/lifgeihcfpkmmlfjbailfpfhbahhibba

**Comment by FallenMax** [comment]
@xyls184  OK I read again and understand the problem now. Can you provide the link to this case? 

Smart TOC prior to version 0.6.0 will insert a "padding" to make page tall enough to scroll to the last heading. If this feature doesn't work properly (or removed), we cannot scroll to last few headings, and then cannot expand them.

But this auto-padding thing is hard to get right (esp. when page load-on-scroll),  so I removed it since 0.6.0, now it seems still necessary... 🤔

**Comment by FallenMax** [comment]
I added `padding` feature back in 0.6.2 which should fix this problem, please take a look! Let me know if it's still not working.
