### ISSUE TITLE
Some header is not displayed

### ISSUE THREAD

**Issue by zawataki** [FallenMax/smart-toc#9]
h1, h2, and h3 title are not displayed on [this gist](https://gist.github.com/zawataki/6921d3a559fc282c2ec2e7c76bdb232b).
But h4 and h5 title are displayed.

**Comment by Lin-Buo-Ren** [comment]
Also reproduced in [markdownlint/configuration.md at master · markdownlint/markdownlint](https://github.com/markdownlint/markdownlint/blob/master/docs/configuration.md)

**Comment by pituach** [comment]
It happens in Microsoft documents as well and it is very annoying. 

for example: 

https://docs.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount

**Comment by wenmin92** [comment]
Also doesn't support [Notion](https://www.notion.so/Learn-the-shortcuts-66e28cec810548c3a4061513126766b0)

**Comment by wenmin92** [comment]
> It happens in Microsoft documents as well and it is very annoying.
> 
> for example:
> 
> https://docs.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount

I have tested this page, and the SmartTOC worked well.

**Comment by wenmin92** [comment]
> Also reproduced in [markdownlint/configuration.md at master · markdownlint/markdownlint](https://github.com/markdownlint/markdownlint/blob/master/docs/configuration.md)

Also worked well.

**Comment by FallenMax** [comment]
@zawataki @pituach @wenmin92 

Smart TOC uses a ranking algorithm to extract article/headings, and it's NOT guaranteed to always work for every website/article in the internet.

The extraction accuracy largely depends on how the article/headings are organized. In general, it should have a larger probability to work if:

1. the website uses html heading tags (h1,h2,h3...) and uses them correctly. Website that uses other tags like `div`, `strong` and `b` will not work (and will not be supported in the future), and that's why it's preferred to always use semantic html. (So Notion doesn't work @wenmin92 )
2. there are more than several headings  (>3?)  for a specific heading level (like h2), so Smart TOC knows they are more likely to be article headings, instead of website sections etc. (So gist by @zawataki doesn't work)

If you find website that not violating these two rules and Smart TOC doesn't work where it should, please open another issue. Thank you for understanding!

**Comment by zawataki** [comment]
@FallenMax Thank you for your clear explanation.
